name: collection_picker
description: A Package contains selectable listview and gridview widgets with support for single, multi, and radio picker types.
version: 1.0.0
repository: https://github.com/nandakista/collection_picker

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.21.0
